from setuptools import setup, find_packages

setup(
    name='pasarelas',
    version='0.1',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'asgiref==3.8.1',
        'channels==4.1.0',
        'Django==5.1.1',
        'djangorestframework==3.15.2',
        'djangorestframework-simplejwt==5.3.1',
        'h11==0.14.0',
        'h2==4.1.0',
        'hpack==4.0.0',
        'Hypercorn==0.17.3',
        'hyperframe==6.0.1',
        'priority==2.0.0',
        'PyJWT==2.9.0',
        'python-dotenv==1.0.1',
        'rest-framework-simplejwt==0.0.2',
        'setuptools==74.1.2',
        'sqlparse==0.5.1',
        'tzdata==2024.1',
        'wsproto==1.2.0',
    ],
    description='A Django app for gateway services',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    author='Jhorman Gallego',
    author_email='jhormangallegogallego@gmail.com',
    url='https://github.com/Hoodinii890/DRFC-pasarelas',
    classifiers=[
        'Environment :: Web Environment',
        'Framework :: Django',
        'Framework :: Django :: 5.1',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3.12',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
    ],
)
