# Generated by Django 5.1.1 on 2025-03-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasarelas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='platform',
            field=models.CharField(choices=[('MP', 'Mercado Pago'), ('Stripe', 'Stripe')], max_length=20, null=True),
        ),
    ]
